name: Setup github repository
on:
  create:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow disable "setup-github.yaml" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
