name: Setup GitHub repository
on:
  create:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download configuration file
        run: curl -fSLo config.json https://raw.githubusercontent.com/AAU-Dat/.github/main/configuration/branch-protection.json
      - name: create branch protection rules for main
        run: gh api -X PUT /repos/${{ github.repository }}/branches/main/protection --input config.json
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
      - name: disable this workflow
        run: gh workflow disable "setup-github.yaml" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
