name: Setup GitHub repository
on:
  create:

jobs:
  configure-github:
    name: Configure GitHub branch protection
    runs-on: ubuntu-latest
    steps:
      - name: Download configuration file
        run: curl -fSLo branch-protection.json https://raw.githubusercontent.com/AAU-Dat/.github/main/configuration/branch-protection.json
      - name: Create branch protection rules for main
        run: gh api -X PUT /repos/${{ github.repository }}/branches/main/protection --input branch-protection.json
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
      - name: Disable this workflow
        run: gh workflow disable --repo ${{ github.repository }} ${{ github.workflow }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
