name: Setup github repository
on:
  create:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, World!"
      - name: Disable action
        run : gh workflow disable "setup-github.yaml"